"""add llm usage tracking tables

Revision ID: 64573bb40ecc
Revises: a9b2f1e5c44d
Create Date: 2026-04-12 14:11:28.618133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64573bb40ecc'
down_revision: Union[str, Sequence[str], None] = 'a9b2f1e5c44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=False),
    sa.Column('response_hash', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('cache_hit', sa.Integer(), nullable=False),
    sa.Column('effort', sa.String(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_records_prompt_hash'), 'llm_usage_records', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_llm_usage_records_step_name'), 'llm_usage_records', ['step_name'], unique=False)
    op.create_table('llm_usage_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usage_record_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('partial_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usage_record_id'], ['llm_usage_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usage_record_id', 'relation_type', 'item_id', 'language_code', 'partial_role', name='uq_usage_link')
    )
    op.create_index(op.f('ix_llm_usage_links_item_id'), 'llm_usage_links', ['item_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_links_language_code'), 'llm_usage_links', ['language_code'], unique=False)
    op.create_index(op.f('ix_llm_usage_links_relation_type'), 'llm_usage_links', ['relation_type'], unique=False)
    op.create_index(op.f('ix_llm_usage_links_usage_record_id'), 'llm_usage_links', ['usage_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_links_usage_record_id'), table_name='llm_usage_links')
    op.drop_index(op.f('ix_llm_usage_links_relation_type'), table_name='llm_usage_links')
    op.drop_index(op.f('ix_llm_usage_links_language_code'), table_name='llm_usage_links')
    op.drop_index(op.f('ix_llm_usage_links_item_id'), table_name='llm_usage_links')
    op.drop_table('llm_usage_links')
    op.drop_index(op.f('ix_llm_usage_records_step_name'), table_name='llm_usage_records')
    op.drop_index(op.f('ix_llm_usage_records_prompt_hash'), table_name='llm_usage_records')
    op.drop_table('llm_usage_records')
    # ### end Alembic commands ###
