"""empty message

Revision ID: a9b2f1e5c44d
Revises: 
Create Date: 2026-04-12 13:38:33.714899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b2f1e5c44d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('asset_key', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'language_code', 'asset_key', name='uq_asset')
    )
    op.create_index(op.f('ix_assets_item_id'), 'assets', ['item_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('general_item_json', sa.Text(), nullable=False),
    sa.Column('target_text_normalized', sa.String(), nullable=True),
    sa.Column('dim_1', sa.String(), nullable=True),
    sa.Column('dim_2', sa.String(), nullable=True),
    sa.Column('dim_3', sa.String(), nullable=True),
    sa.Column('dim_4', sa.String(), nullable=True),
    sa.Column('dim_5', sa.String(), nullable=True),
    sa.Column('dim_6', sa.String(), nullable=True),
    sa.Column('dim_7', sa.String(), nullable=True),
    sa.Column('dim_8', sa.String(), nullable=True),
    sa.Column('grammar_id', sa.String(), nullable=True),
    sa.Column('grammar_parameters_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'language_code', name='uq_branch')
    )
    op.create_index(op.f('ix_branches_dim_1'), 'branches', ['dim_1'], unique=False)
    op.create_index(op.f('ix_branches_dim_2'), 'branches', ['dim_2'], unique=False)
    op.create_index(op.f('ix_branches_dim_3'), 'branches', ['dim_3'], unique=False)
    op.create_index(op.f('ix_branches_dim_4'), 'branches', ['dim_4'], unique=False)
    op.create_index(op.f('ix_branches_dim_5'), 'branches', ['dim_5'], unique=False)
    op.create_index(op.f('ix_branches_dim_6'), 'branches', ['dim_6'], unique=False)
    op.create_index(op.f('ix_branches_dim_7'), 'branches', ['dim_7'], unique=False)
    op.create_index(op.f('ix_branches_dim_8'), 'branches', ['dim_8'], unique=False)
    op.create_index(op.f('ix_branches_grammar_id'), 'branches', ['grammar_id'], unique=False)
    op.create_index(op.f('ix_branches_item_id'), 'branches', ['item_id'], unique=False)
    op.create_index(op.f('ix_branches_language_code'), 'branches', ['language_code'], unique=False)
    op.create_index(op.f('ix_branches_target_text_normalized'), 'branches', ['target_text_normalized'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('text_normalized', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('canonical_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_text_normalized'), 'items', ['text_normalized'], unique=False)
    op.create_table('lesson_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'language_code', 'item_id', name='uq_lesson_item')
    )
    op.create_index(op.f('ix_lesson_items_item_id'), 'lesson_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_lesson_items_lesson_id'), 'lesson_items', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_items_lesson_id'), table_name='lesson_items')
    op.drop_index(op.f('ix_lesson_items_item_id'), table_name='lesson_items')
    op.drop_table('lesson_items')
    op.drop_index(op.f('ix_items_text_normalized'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_branches_target_text_normalized'), table_name='branches')
    op.drop_index(op.f('ix_branches_language_code'), table_name='branches')
    op.drop_index(op.f('ix_branches_item_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_grammar_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_8'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_7'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_6'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_5'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_4'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_3'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_2'), table_name='branches')
    op.drop_index(op.f('ix_branches_dim_1'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_assets_item_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
