"""
Pydantic data models for Japanese lesson content.

These schemas define the shapes of LLM-generated data used across the pipeline
and serialised to output/<lesson_id>/content.json by lesson_store.py.

Compilation pipeline models (CompiledItem, Touch) define the data shapes for
the three-stage transformation: item_sequence → compiled_items → touch_sequence.
"""

from __future__ import annotations

from enum import Enum
from pathlib import Path
from typing import Any, Union

from pydantic import BaseModel, ConfigDict, Field, model_validator


class _NullStrCoerce(BaseModel):
    """Mixin: convert any None value for a field declared as str to ''.

    Handles LLMs that return ``null`` for optional-feeling string fields
    (e.g. ``notes``, ``memory_tip``) instead of omitting them or using ``""``.
    """

    @model_validator(mode="before")
    @classmethod
    def _coerce_null_strings(cls, data: object) -> object:
        if not isinstance(data, dict):
            return data
        annotations = {}
        for klass in reversed(cls.__mro__):
            annotations.update(getattr(klass, "__annotations__", {}))
        for field, annotation in annotations.items():
            if annotation is str and data.get(field) is None:
                data[field] = ""
        return data


class PartialItem(BaseModel):

    display_text: str = ""
    tts_text: str = ""
    pronunciation: str = ""
    extra: dict[str, Any] = Field(default_factory=dict)
    assets: dict[str, Path] = Field(default_factory=dict)
    

class GeneralItem(_NullStrCoerce):
    """A general lesson item with flexible fields for any language pair.

    This is used as an intermediate type for LLM responses before validation
    and transformation into the more specific NounItem / VerbItem / Sentence
    models.  It allows the LLM to return extra fields without causing parsing
    errors, which is useful for accommodating different language pairs with
    varying requirements.
    """
    id: str = ""
    canonical_text: str = ""
    source: PartialItem = Field(default_factory=PartialItem)
    target: PartialItem = Field(default_factory=PartialItem)
    assets: dict[str, Path] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional arbitrary metadata from the LLM, preserved for flexibility.")
    block_index: int = 1
    phase: Phase | None = None

    @model_validator(mode="before")
    @classmethod
    def _coerce_legacy_item_type(cls, data: object) -> object:
        if not isinstance(data, dict):
            return data
        if data.get("phase"):
            return data
        legacy_item_type = data.get("item_type")
        legacy_phase_map = {
            "noun": "nouns",
            "verb": "verbs",
            "sentence": "grammar",
        }
        if isinstance(legacy_item_type, str):
            legacy_phase = legacy_phase_map.get(legacy_item_type.strip().lower())
            if legacy_phase:
                data["phase"] = legacy_phase
        return data


class NounItem(GeneralItem):
    """A vocabulary noun enriched with examples and a memory tip by the LLM.

    Extra fields (e.g. ``hungarian``, ``pronunciation`` for hun-eng lessons)
    are preserved transparently so the model round-trips correctly for all
    language pairs without requiring a separate type.
    """


class VerbItem(GeneralItem):
    """A vocabulary verb with conjugation forms and a memory tip from the LLM.

    Extra fields (e.g. ``hungarian``, ``pronunciation``, ``past_tense`` for
    hun-eng lessons) are preserved transparently so the model round-trips
    correctly for all language pairs.
    """


class Sentence(GeneralItem):
    """A grammar practice sentence generated by the LLM.

    Extra fields (e.g. ``hungarian`` for hun-eng lessons) are preserved
    transparently in serialization so all language pairs round-trip correctly.
    """

    grammar_id: str = ""
    grammar_parameters: dict[str, str] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _coerce_grammar_parameters(cls, data: object) -> object:
        """Coerce None values in grammar_parameters to empty strings.

        Some LLM responses may include nulls for optional parameters; this
        prevents Pydantic validation errors while keeping the dictionary
        structure intact.
        """
        if not isinstance(data, dict):
            return data
        gp = data.get("grammar_parameters")
        if isinstance(gp, dict):
            data["grammar_parameters"] = {
                k: (v if v is not None else "") for k, v in gp.items()
            }
        return data


class NarrativeVocabBlock(BaseModel):
    """Vocabulary terms extracted from one narrative block.

    Produced by ``ExtractNarrativeVocabStep`` and consumed by ``SelectVocabStep``.
    Replaces the raw ``dict[str, list[str]]`` representation so that downstream
    steps get proper attribute access and Pydantic validation instead of
    silent key-miss fallbacks.
    """

    nouns: list[str] = Field(default_factory=list)
    verbs: list[str] = Field(default_factory=list)


class VocabItem(BaseModel):
    """A single vocabulary entry within a VocabFile.

    Language-specific fields (e.g. ``english``, ``japanese``, ``romaji``) are
    preserved as-is via ``extra='allow'`` and surfaced through ``model_dump()``
    so that ``ItemGenerator.convert_raw_noun/verb`` continue to work unchanged.
    """

    model_config = ConfigDict(extra="allow")

    id: str = ""
    source: str = ""
    target: str = ""
    phonetic: str = ""


class VocabFile(BaseModel):
    """Typed representation of a theme vocab file (nouns + verbs).

    Replaces the raw ``dict`` previously stored in ``LessonContext.vocab``,
    giving typed attribute access to ``.nouns`` and ``.verbs`` while remaining
    fully round-trippable through ``model_validate`` / ``model_dump``.
    """

    theme: str = ""
    nouns: list[VocabItem] = Field(default_factory=list)
    verbs: list[VocabItem] = Field(default_factory=list)


class GrammarItem(BaseModel):
    """A grammar progression item with generalized fields.

    Used for both eng-jap and hun-eng grammar progressions.
    """
    id: str
    pattern: str
    description: str
    example_source: str
    example_target: str
    requires: list[str] = Field(default_factory=list)
    level: int = 1


class LessonContent(BaseModel):
    """Full structured content for one lesson — persisted to content.json."""

    lesson_id: int
    theme: str
    language: str = "eng-jap"
    narrative_blocks: list[str] = Field(default_factory=list)
    grammar_ids: list[str] = Field(default_factory=list)
    words: list[GeneralItem] = Field(default_factory=list)
    sentences: list[Sentence] = Field(default_factory=list)
    created_at: str = ""

    @property
    def noun_items(self) -> list[GeneralItem]:
        """Nouns from the words list."""
        return [w for w in self.words if w.phase == Phase.NOUNS]

    @property
    def verb_items(self) -> list[GeneralItem]:
        """Verbs from the words list."""
        return [w for w in self.words if w.phase == Phase.VERBS]


# ---------------------------------------------------------------------------
# Compilation pipeline models (Stages 2–3)
# ---------------------------------------------------------------------------


class Phase(str, Enum):
    """Lesson phase — determines which repetition cycle applies."""

    NOUNS = "nouns"
    VERBS = "verbs"
    GRAMMAR = "grammar"


class TouchType(str, Enum):
    """Mechanical specification of a single touch interaction."""

    # Card-based (visual prompt → visual reveal)
    SOURCE_TARGET = "source→target"
    TARGET_SOURCE = "target→source"
    SOURCE_ONLY = "source only"
    TARGET_ONLY = "target only"

    # Listen-first (audio-led, passive-friendly)
    LISTEN_DUAL_M = "listen dual (s:m;t:f/m)" # source male voice, target: female, male voice
    LISTEN_DUAL_F = "listen dual (s:f;t:m/f)" # source female voice, target: male, female voice
    LISTEN_REVERSE_M = "listen reverse (t:m;s:m)" # target male voice, source male voice
    LISTEN_REVERSE_F = "listen reverse (t:f;s:f)" # target female voice, source female voice
    LISTEN_TARGET_M =    "listen target only (t:m)" # target male voice only
    LISTEN_TARGET_F =    "listen target only (t:f)" # target female voice only


class TouchIntent(str, Enum):
    """Pedagogical intent of a touch within a repetition cycle."""

    INTRODUCE = "introduce"
    RECALL = "recall"
    REINFORCE = "reinforce"
    CONFIRM = "confirm"
    LOCK_IN = "lock-in"
    TRANSLATE = "translate"
    COMPREHEND = "comprehend"
    UNKNOWN = "---"

    def show_source(self) -> bool:
        return self in [
            TouchIntent.INTRODUCE, 
            TouchIntent.RECALL,
            TouchIntent.REINFORCE,
            TouchIntent.CONFIRM,
            TouchIntent.COMPREHEND,
            TouchIntent.UNKNOWN,
        ]
    
    def show_target(self) -> bool:
        return self in [
            TouchIntent.INTRODUCE, 
            TouchIntent.RECALL, 
            TouchIntent.TRANSLATE, 
            TouchIntent.CONFIRM,
            TouchIntent.UNKNOWN,
        ]


class RepetitionStep(BaseModel):
    """One step in a repetition cycle: a touch type paired with its intent."""

    touch_type: TouchType
    intent: TouchIntent


class ItemAssets(GeneralItem): 
    pass
# **Use general item assets dict instead**
#     """Rendered asset paths for a single item. Populated by the asset compiler."""

#     card_src: Path | None = None
#     card_tar: Path | None = None
#     card_src_tar: Path | None = None
#     audio_src: Path | None = None
#     audio_tar_f: Path | None = None
#     audio_tar_m: Path | None = None

#     model_config = {"arbitrary_types_allowed": True}


LessonItem = Union[NounItem, VerbItem, Sentence]


class CompiledItem(GeneralItem): 
    pass
# **Use GeneralItem with assets dict instead**
#     """An item with all its rendered assets — output of Stage 2 (asset compiler)."""

#     item: NounItem | VerbItem | Sentence
#     phase: Phase
#     assets: ItemAssets = Field(default_factory=ItemAssets)

# #     model_config = {"arbitrary_types_allowed": True}


class VideoCard(BaseModel):
    """One card item for the simple video rendering pipeline."""

    phase: str
    step: str
    counter: str
    prompt: str
    reveal: str
    tts_text: str
    tts_voice: str = ""


class Touch(BaseModel):
    """One learner interaction — output of Stage 3 (touch compiler).

    References a GeneralItem and specifies which assets to use.
    """
    touch_index: int
    phase: Phase

    item: GeneralItem = Field(default_factory=GeneralItem)
    touch_type: TouchType
    intent: TouchIntent

    artifacts: dict[str, Path | list[Path]] = Field(default_factory=dict)

    model_config = {"arbitrary_types_allowed": True}
