"""
Pydantic data models for Japanese lesson content.

These schemas define the shapes of LLM-generated data used across the pipeline
and serialised to output/<lesson_id>/content.json by lesson_store.py.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class NounItem(BaseModel):
    """A vocabulary noun enriched with examples and a memory tip by the LLM."""

    english: str = ""
    japanese: str = ""
    kanji: str = ""
    romaji: str = ""
    example_sentence_jp: str = ""
    example_sentence_en: str = ""
    memory_tip: str = ""


class VerbItem(BaseModel):
    """A vocabulary verb with conjugation forms and a memory tip from the LLM."""

    english: str = ""
    japanese: str = ""
    kanji: str = ""
    romaji: str = ""
    masu_form: str = ""
    polite_forms: dict[str, str] = Field(default_factory=dict)
    example_sentence_jp: str = ""
    example_sentence_en: str = ""
    memory_tip: str = ""


class Sentence(BaseModel):
    """A grammar practice sentence generated by the LLM."""

    grammar_id: str = ""
    english: str = ""
    japanese: str = ""
    romaji: str = ""
    person: str = ""
    notes: str = ""


class LessonContent(BaseModel):
    """Full structured content for one lesson — persisted to content.json."""

    lesson_id: int
    theme: str
    grammar_ids: list[str] = Field(default_factory=list)
    noun_items: list[NounItem] = Field(default_factory=list)
    verb_items: list[VerbItem] = Field(default_factory=list)
    sentences: list[Sentence] = Field(default_factory=list)
    created_at: str = ""
